import { readFileSync, existsSync } from "fs";
import { join } from "path";
import { ConfigSchema, type Config } from "./config.schema.js";

const CONFIG_FILE_NAME = "config.json";

export function loadConfig(): Config {
  // Priority: env vars > MCP_CONFIG_PATH file > cwd/config.json > defaults
  const configPath =
    process.env["MCP_CONFIG_PATH"] ?? join(process.cwd(), CONFIG_FILE_NAME);

  let rawConfig: Record<string, unknown> = {};

  if (existsSync(configPath)) {
    const fileContent = readFileSync(configPath, "utf-8");
    try {
      rawConfig = JSON.parse(fileContent) as Record<string, unknown>;
    } catch {
      throw new Error(
        `Invalid JSON in ${configPath}. Check for syntax errors (trailing commas, missing quotes).`,
      );
    }
  }

  // Override with env vars if present.
  // Accepts both SCREAMING_SNAKE_CASE (documented, server.json) and camelCase
  // (generated by VS Code when it reads config.example.json from the npm package).
  const envUrl = process.env["DATAVERSE_ENV_URL"] ?? process.env["environmentUrl"];
  if (envUrl) rawConfig["environmentUrl"] = envUrl;

  const authMode = process.env["AUTH_MODE"] ?? process.env["authMode"];
  if (authMode) rawConfig["authMode"] = authMode;

  const pacProfile = process.env["PAC_PROFILE_NAME"] ?? process.env["pacProfileName"];
  if (pacProfile) rawConfig["pacProfileName"] = pacProfile;

  const tenantId = process.env["TENANT_ID"] ?? process.env["tenantId"];
  if (tenantId) rawConfig["tenantId"] = tenantId;

  const clientId = process.env["CLIENT_ID"] ?? process.env["clientId"];
  if (clientId) rawConfig["clientId"] = clientId;

  const clientSecret = process.env["CLIENT_SECRET"] ?? process.env["clientSecret"];
  if (clientSecret) rawConfig["clientSecret"] = clientSecret;

  const timeoutMs =
    process.env["REQUEST_TIMEOUT_MS"] ?? process.env["requestTimeoutMs"];
  if (timeoutMs) rawConfig["requestTimeoutMs"] = Number(timeoutMs);

  const maxRetries = process.env["MAX_RETRIES"] ?? process.env["maxRetries"];
  if (maxRetries) rawConfig["maxRetries"] = Number(maxRetries);

  const result = ConfigSchema.safeParse(rawConfig);

  if (!result.success) {
    throw new Error(
      `Invalid configuration:\n${result.error.issues.map((i) => `  - ${i.path.join(".")}: ${i.message}`).join("\n")}`,
    );
  }

  return result.data;
}
